### ISSUE TITLE
Error while updating prop selectionColor

### ISSUE THREAD

**Issue by RoWaiR** [react-native-training/react-native-elements#1197]
## Error

E/unknown:ViewManager: Error while updating prop selectionColor
                                                        java.lang.reflect.InvocationTargetException
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:80)
                                                            at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129)
                                                            at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48)
                                                            at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34)
                                                            at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:214)
                                                            at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153)
                                                            at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1006)
                                                            at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:977)
                                                            at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
                                                            at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
                                                            at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                            at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                            at android.os.Looper.loop(Looper.java:148)
                                                            at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                         Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                            at android.content.res.Resources.getValue(Resources.java:2596)
                                                            at android.content.res.Resources.getDrawable(Resources.java:2039)
                                                            at android.content.res.Resources.getDrawable(Resources.java:2025)
                                                            at android.content.Context.getDrawable(Context.java:464)
                                                            at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:358)
                                                            at com.facebook.react.views.textinput.ReactTextInputManager.setCursorColor(ReactTextInputManager.java:334)
                                                            at com.facebook.react.views.textinput.ReactTextInputManager.setSelectionColor(ReactTextInputManager.java:321)
                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                            at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:80) 
                                                            at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129) 
                                                            at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48) 
                                                            at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34) 
                                                            at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:214) 
                                                            at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153) 
                                                            at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1006) 
                                                            at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:977) 
                                                            at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31) 
                                                            at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136) 
                                                            at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107) 
                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909) 
                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:686) 
                                                            at android.view.Choreographer.doFrame(Choreographer.java:619) 
                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897) 
                                                            at android.os.Handler.handleCallback(Handler.java:739) 
                                                            at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                            at android.os.Looper.loop(Looper.java:148) 
                                                            at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 

 E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.wupplier.app, PID: 22280
                                                   com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'selectionColor' of a view managed by: AndroidTextInput
                                                       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:92)
                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129)
                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48)
                                                       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34)
                                                       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:214)
                                                       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153)
                                                       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1006)
                                                       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:977)
                                                       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
                                                       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
                                                       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:80)
                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129) 
                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48) 
                                                       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34) 
                                                       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:214) 
                                                       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153) 
                                                       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1006) 
                                                       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:977) 
                                                       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31) 
                                                       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136) 
                                                       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107) 
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909) 
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:686) 
                                                       at android.view.Choreographer.doFrame(Choreographer.java:619) 
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897) 
                                                       at android.os.Handler.handleCallback(Handler.java:739) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                    Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                       at android.content.res.Resources.getValue(Resources.java:2596)
                                                       at android.content.res.Resources.getDrawable(Resources.java:2039)
                                                       at android.content.res.Resources.getDrawable(Resources.java:2025)
                                                       at android.content.Context.getDrawable(Context.java:464)
                                                       at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:358)
                                                       at com.facebook.react.views.textinput.ReactTextInputManager.setCursorColor(ReactTextInputManager.java:334)
                                                       at com.facebook.react.views.textinput.ReactTextInputManager.setSelectionColor(ReactTextInputManager.java:321)
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:80) 
                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129) 
                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48) 
                                                       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34) 
                                                       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:214) 
                                                       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153) 
                                                       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1006) 
                                                       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:977) 
                                                       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31) 
                                                       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136) 
                                                       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107) 
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909) 
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:686) 
                                                       at android.view.Choreographer.doFrame(Choreographer.java:619) 
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897) 
                                                       at android.os.Handler.handleCallback(Handler.java:739) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 

Depenencias

>   "dependencies": {
    "@expo/vector-icons": "^6.3.1",
    "axios": "^0.16.2",
    "ex-react-native-i18n": "0.0.3",
    "expo": "23.0.0",
    "lodash": "^4.17.4",
    "moment": "^2.19.2",
    "numeral": "^2.0.6",
    "prop-types": "^15.5.10",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz",
    "react-native-action-button": "^2.8.2",
    "react-native-action-picker": "^1.0.1",
    "react-native-calendars": "^1.15.0",
    "react-native-circular-progress": "github:bgryszko/react-native-circular-progress#91f15f5a5320c04d645352a629f2478873344f6d",
    "react-native-datepicker": "^1.6.0",
    "react-native-elements": "^0.18.0",
    "react-native-gifted-chat": "^0.3.0",
    "react-native-globalize": "^1.2.3",
    "react-native-keyboard-aware-scrollview": "^1.1.7",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-render-html": "^3.8.1",
    "react-native-router-flux": "^4.0.0-beta.24",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-persist": "^4.10.2",
    "redux-thunk": "^2.2.0"
  }

Unlinked from expo

It only happens on android, when I create the release in debug it does not fail me.

**Comment by xavier-villelegier** [comment]
@RoWaiR There are no references to `react-native-elements` in the stacktrace you provided. Why do you think this is related to RNE ? Which component are you using that can cause this error ?

Also, you should update to the latest version of RNE

**Comment by RoWaiR** [comment]
I am using "react-native-elements": "^ 0.18.0"

It only happens when I create the apk in release mode

**Comment by xavier-villelegier** [comment]
@RoWaiR Yea but there are no references to RNE in your error, why do you think this error occurs because of RNE ? 🤔

**Comment by RoWaiR** [comment]
For the error that the selectionColor gives me, looking for information I saw related errors.

**Comment by RoWaiR** [comment]
I just tried v0.19.1 and I still get the same thing, it's not uncommon that I only get the error in release and in debug work perfect ...

**Comment by xavier-villelegier** [comment]
Which components of RNE are you using ?

**Comment by RoWaiR** [comment]
import { FormLabel, FormInput, Button, FormValidationMessage } from 'react-native-elements';

**Comment by xavier-villelegier** [comment]
@RoWaiR Sorry for the delay, did you finally find what was causing the issue ?

**Comment by xavier-villelegier** [comment]
Closing this for inactivity
