### ISSUE TITLE
Unable to resolve module 'react-native-vector-icons/Materiallcons

### ISSUE THREAD

**Issue by JamesBondPc** [react-native-training/react-native-elements#412]
Loading dependency graph, done.
error: bundling: UnableToResolveError: Unable to resolve module `react-native-vector-icons/MaterialIcons` from `/Users/jamesbond/WebstormProjects/Menu/node_modules/react-native-elements/src/buttons/Button.js`: Module does not exist in the module map or in these directories:
  /Users/jamesbond/WebstormProjects/Menu/node_modules/react-native-elements/node_modules/react-native-vector-icons
,   /Users/jamesbond/WebstormProjects/Menu/node_modules/react-native-vector-icons
,   /Users/jamesbond/node_modules/react-native-vector-icons

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
    at ResolutionRequest._resolveNodeDependency (/Users/jamesbond/WebstormProjects/Menu/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:470:11)
    at ResolutionRequest.resolveDependency (/Users/jamesbond/WebstormProjects/Menu/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:135:29)
    at dependencyNames.map.name (/Users/jamesbond/WebstormProjects/Menu/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:142:59)
    at Array.map (native)
    at ResolutionRequest.resolveModuleDependencies (/Users/jamesbond/WebstormProjects/Menu/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:142:42)
    at Promise.resolve.then (/Users/jamesbond/WebstormProjects/Menu/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:179:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
Bundling `index.ios.js`  0.0% (5/439), failed.

**Comment by buncismamen** [comment]
have u installed it?
https://github.com/oblador/react-native-vector-icons

**Comment by Monte9** [comment]
@JamesBondPc Please see @buncismamen answer above. It should resolve the issue you are facing. If not, please feel free to open this issue again and we can help you resolve it.

**Comment by violy** [comment]
I've the same issue. works fine with @buncismamen answer. Thanks.

**Comment by lustigdev** [comment]
@buncismamen I got 404 from your follow this link, but here is an updated link to installation instructions: Unable to resolve module `react-native-vector-icons/MaterialIcons

**Comment by Sunethotagamuwa** [comment]
I resolved it by importing the react-native-vector-icons manually

Instead of:
import Icon from 'react-native-vector-icons';

Use:
import Icon from '../../node_modules/react-native-vector-icons/MaterialIcons';


(PS: the directory may vary according to the folder structure)

**Comment by Bhupindersingh12** [comment]
npm install --save react-native-vector-icons
npm ERR! Cannot read property 'match' of undefined
 i m facing this error
