### ISSUE TITLE
Errors with shallow enzyme test

### ISSUE THREAD

**Issue by pricetula** [react-native-training/react-native-elements#536]
Unit testing component to check if its Grid type using enzyme "shallow".
__tests__/component/component.spec.js
```
import { Grid } from 'react-native-elements';

import Component from '../Component';

describe('<Component />', () => {
  const testTarget = shallow(<Component />);
  it('rendered ok', () => {
    assert.equal(
      testTarget.type(),
      Grid,
      'Component did not ok'
    );
  });
});
```
My setup works with testing react native components. However the test don't run at all when i import react-native-elements into my spec file, I get the error below.
```
Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
/app/node_modules/react-native-elements/src/index.js:2
import Button from './buttons/Button';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Module._load (module.js:438:3)
    at Function.hookedLoader [as _load] (/app/mocha-setup.js:13:10)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/__tests__/mocha/component/ComponentHome.spec.js:1:1)
    at Module._compile (module.js:570:32)
    at loader (/app/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Module._load (module.js:438:3)
    at Function.hookedLoader [as _load] (/app/mocha-setup.js:13:10)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /app/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/app/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/app/node_modules/mocha/lib/mocha.js:513:10)
    at Object.<anonymous> (/app/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
error Command failed with exit code 1.
```
react-native-elements = 0.15.0
react = 16.0.0-alpha.6
react-native = 0.44.1

**Comment by rdamborsky** [comment]
Same here. I'm just importing a different component.

```
"react": "16.0.0-alpha.12",
"react-native": "0.45.1",
```

my .babelrc presets: `"presets": ["react-native", "react", "env"],`

**Comment by Monte9** [comment]
Hmm.. not sure how to resolve this.

@binoy14 @iRoachie thoughts on this?

**Comment by binoy14** [comment]
What version of enzyme are you using? It has to be the right version based on your react native version since the test utils was moved to a different package

**Comment by pricetula** [comment]
Hi thanks for response.
enzyme 2.9.1

**Comment by iRoachie** [comment]
Closing this as inactive as there's been no activity for over 30 days. If the problem re-occurs on the latest version of react-native-elements then ping me to reopen or create a new issue. 
Thanks.

**Comment by joannaKasinska** [comment]
I have same problem:
`
"react": "16.0.0-beta.5",
"react-native": "0.49.3",
"chai": "^4.1.2",
"enzyme": "^2.9.1",
"mocha": "^4.0.1",
`
Has anyone solved the problem?

**Comment by henriqueViana** [comment]
I had this problem too, but I managed to solve.

My .babelrc presets 
"presets": ["es2015", "react-native", "react"];

My devDependencies
"react": "15.4.2",
"react-native": "0.49.3",
"chai-enzyme": "^0.8.0",
"enzyme": "^3.3.0",
"mocha": "^4.1.0"

And run with this npm script
"test": "./node_modules/.bin/mocha --compilers js:babel-core/register __tests__/*.spec.js"

**Comment by ridgekimani** [comment]
@joannaKasinska I don't know if you solved the issue but I realized that the issue is with `mocha` itself. I don't know how @henriqueViana got it to work but if it did, trying to install other `react-native` packages would result to errors. This is because, ideally most packages are `linked` to native code but mocha runs the tests like it's on a browser interface. However, if you use `jest`, it does all the linking and therefore these packaging errors wouldn't occur.

**Comment by geminiyellow** [comment]
Same error, anybody can tell me what is happend here ?
